# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_Review', '0002_auto_20190620_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='nickname',
        ),
    ]
