# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_Review', '0003_auto_20190620_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
