# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_Review', '0004_auto_20190620_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
