# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_Review', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
