# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_Review', '0011_auto_20190623_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
